MONTH_CHOICES = [
    (1, 'January'),
    (2, 'February'),
    (3, 'March'),
    (4, 'April'),
    (5, 'May'),
    (6, 'June'),
    (7, 'July'),
    (8, 'August'),
    (9, 'September'),
    (10, 'October'),
    (11, 'November'),
    (12, 'December'),
]

WRK_STATUS_CHOICES = [
    (0, 'Active'),
    (1, 'Retired'),
    (2, 'Dead')
]
CMP_STATUS_CHOICES = [
    (0, 'Opened'),
    (1, 'Closed'),
]

# Wrestling Styles
STYLE_CHOICES = [
    ('all-rounder', 'All-Rounder'),
    ('brawler', 'Brawler'),
    ('comedy', 'Comedy'),
    ('gimmick', 'Gimmick'),
    ('hardcore', 'Hardcore'),
    ('high Flyer', 'High Flyer'),
    ('luchador', 'Luchador'),
    ('powerhouse', 'Powerhouse'),
    ('showman', 'Showman'),
    ('strong style', 'Strong Style'),
    ('technician', 'Technician'),
    ('other', 'Other'),
]

RELATIONSHIP_CHOICES = [
    ('friends', 'Friends'),
    ('rivals', 'Rivals'),
    ('lovers', 'Lovers'),
    ('pupil', 'Pupil'),
]

NATIONALITY_CHOICES = [
    ('Afghanistan', 'Afghanistan'),
    ('Aland Islands', 'Aland Islands'),
    ('Albania', 'Albania'),
    ('Algeria', 'Algeria'),
    ('American Samoa', 'American Samoa'),
    ('Andorra', 'Andorra'),
    ('Angola', 'Angola'),
    ('Anguilla', 'Anguilla'),
    ('Antarctica', 'Antarctica'),
    ('Antigua and Barbuda', 'Antigua and Barbuda'),
    ('Argentina', 'Argentina'),
    ('Armenia', 'Armenia'),
    ('Aruba', 'Aruba'),
    ('Australia', 'Australia'),
    ('Austria', 'Austria'),
    ('Azerbaijan', 'Azerbaijan'),
    ('Bahamas', 'Bahamas'),
    ('Bahrain', 'Bahrain'),
    ('Bangladesh', 'Bangladesh'),
    ('Barbados', 'Barbados'),
    ('Belarus', 'Belarus'),
    ('Belgium', 'Belgium'),
    ('Belize', 'Belize'),
    ('Benin', 'Benin'),
    ('Bermuda', 'Bermuda'),
    ('Bhutan', 'Bhutan'),
    ('Bolivia, Plurinational State of', 'Bolivia, Plurinational State of'),
    ('Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba'),
    ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'),
    ('Botswana', 'Botswana'),
    ('Bouvet Island', 'Bouvet Island'),
    ('Brazil', 'Brazil'),
    ('British Indian Ocean Territory', 'British Indian Ocean Territory'),
    ('Brunei Darussalam', 'Brunei Darussalam'),
    ('Bulgaria', 'Bulgaria'),
    ('Burkina Faso', 'Burkina Faso'),
    ('Burundi', 'Burundi'),
    ('Cambodia', 'Cambodia'),
    ('Cameroon', 'Cameroon'),
    ('Canada', 'Canada'),
    ('Cape Verde', 'Cape Verde'),
    ('Cayman Islands', 'Cayman Islands'),
    ('Central African Republic', 'Central African Republic'),
    ('Chad', 'Chad'),
    ('Chile', 'Chile'),
    ('China', 'China'),
    ('Christmas Island', 'Christmas Island'),
    ('Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'),
    ('Colombia', 'Colombia'),
    ('Comoros', 'Comoros'),
    ('Congo', 'Congo'),
    ('Congo, The Democratic Republic of the',
     'Congo, The Democratic Republic of the'),
    ('Cook Islands', 'Cook Islands'),
    ('Costa Rica', 'Costa Rica'),
    ('Côte d\'Ivoire', 'Côte d\'Ivoire'),
    ('Croatia', 'Croatia'),
    ('Cuba', 'Cuba'),
    ('Curaçao', 'Curaçao'),
    ('Cyprus', 'Cyprus'),
    ('Czech Republic', 'Czech Republic'),
    ('Denmark', 'Denmark'),
    ('Djibouti', 'Djibouti'),
    ('Dominica', 'Dominica'),
    ('Dominican Republic', 'Dominican Republic'),
    ('Ecuador', 'Ecuador'),
    ('Egypt', 'Egypt'),
    ('El Salvador', 'El Salvador'),
    ('Equatorial Guinea', 'Equatorial Guinea'),
    ('Eritrea', 'Eritrea'),
    ('Estonia', 'Estonia'),
    ('Ethiopia', 'Ethiopia'),
    ('Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)'),
    ('Faroe Islands', 'Faroe Islands'),
    ('Fiji', 'Fiji'),
    ('Finland', 'Finland'),
    ('France', 'France'),
    ('French Guiana', 'French Guiana'),
    ('French Polynesia', 'French Polynesia'),
    ('French Southern Territories', 'French Southern Territories'),
    ('Gabon', 'Gabon'),
    ('Gambia', 'Gambia'),
    ('Georgia', 'Georgia'),
    ('Germany', 'Germany'),
    ('Ghana', 'Ghana'),
    ('Gibraltar', 'Gibraltar'),
    ('Greece', 'Greece'),
    ('Greenland', 'Greenland'),
    ('Grenada', 'Grenada'),
    ('Guadeloupe', 'Guadeloupe'),
    ('Guam', 'Guam'),
    ('Guatemala', 'Guatemala'),
    ('Guernsey', 'Guernsey'),
    ('Guinea', 'Guinea'),
    ('Guinea-Bissau', 'Guinea-Bissau'),
    ('Guyana', 'Guyana'),
    ('Haiti', 'Haiti'),
    ('Heard Island and McDonald Islands', 'Heard Island and McDonald Islands'),
    ('Holy See (Vatican City State)', 'Holy See (Vatican City State)'),
    ('Honduras', 'Honduras'),
    ('Hong Kong', 'Hong Kong'),
    ('Hungary', 'Hungary'),
    ('Iceland', 'Iceland'),
    ('India', 'India'),
    ('Indonesia', 'Indonesia'),
    ('Iran, Islamic Republic of', 'Iran, Islamic Republic of'),
    ('Iraq', 'Iraq'),
    ('Ireland', 'Ireland'),
    ('Isle of Man', 'Isle of Man'),
    ('Israel', 'Israel'),
    ('Italy', 'Italy'),
    ('Jamaica', 'Jamaica'),
    ('Japan', 'Japan'),
    ('Jersey', 'Jersey'),
    ('Jordan', 'Jordan'),
    ('Kazakhstan', 'Kazakhstan'),
    ('Kenya', 'Kenya'),
    ('Kiribati', 'Kiribati'),
    ('Korea, Democratic People\'s Republic of',
     'Korea, Democratic People\'s Republic of'),
    ('Korea, Republic of', 'Korea, Republic of'),
    ('Kuwait', 'Kuwait'),
    ('Kyrgyzstan', 'Kyrgyzstan'),
    ('Lao People\'s Democratic Republic', 'Lao People\'s Democratic Republic'),
    ('Latvia', 'Latvia'),
    ('Lebanon', 'Lebanon'),
    ('Lesotho', 'Lesotho'),
    ('Liberia', 'Liberia'),
    ('Libya', 'Libya'),
    ('Liechtenstein', 'Liechtenstein'),
    ('Lithuania', 'Lithuania'),
    ('Luxembourg', 'Luxembourg'),
    ('Macao', 'Macao'),
    ('Macedonia, Republic of', 'Macedonia, Republic of'),
    ('Madagascar', 'Madagascar'),
    ('Malawi', 'Malawi'),
    ('Malaysia', 'Malaysia'),
    ('Maldives', 'Maldives'),
    ('Mali', 'Mali'),
    ('Malta', 'Malta'),
    ('Marshall Islands', 'Marshall Islands'),
    ('Martinique', 'Martinique'),
    ('Mauritania', 'Mauritania'),
    ('Mauritius', 'Mauritius'),
    ('Mayotte', 'Mayotte'),
    ('Mexico', 'Mexico'),
    ('Micronesia, Federated States of', 'Micronesia, Federated States of'),
    ('Moldova, Republic of', 'Moldova, Republic of'),
    ('Monaco', 'Monaco'),
    ('Mongolia', 'Mongolia'),
    ('Montenegro', 'Montenegro'),
    ('Montserrat', 'Montserrat'),
    ('Morocco', 'Morocco'),
    ('Mozambique', 'Mozambique'),
    ('Myanmar', 'Myanmar'),
    ('Namibia', 'Namibia'),
    ('Nauru', 'Nauru'),
    ('Nepal', 'Nepal'),
    ('Netherlands', 'Netherlands'),
    ('New Caledonia', 'New Caledonia'),
    ('New Zealand', 'New Zealand'),
    ('Nicaragua', 'Nicaragua'),
    ('Niger', 'Niger'),
    ('Nigeria', 'Nigeria'),
    ('Niue', 'Niue'),
    ('Norfolk Island', 'Norfolk Island'),
    ('Northern Mariana Islands', 'Northern Mariana Islands'),
    ('Norway', 'Norway'),
    ('Oman', 'Oman'),
    ('Pakistan', 'Pakistan'),
    ('Palau', 'Palau'),
    ('Palestinian Territory, Occupied', 'Palestinian Territory, Occupied'),
    ('Panama', 'Panama'),
    ('Papua New Guinea', 'Papua New Guinea'),
    ('Paraguay', 'Paraguay'),
    ('Peru', 'Peru'),
    ('Philippines', 'Philippines'),
    ('Pitcairn', 'Pitcairn'),
    ('Poland', 'Poland'),
    ('Portugal', 'Portugal'),
    ('Puerto Rico', 'Puerto Rico'),
    ('Qatar', 'Qatar'),
    ('Réunion', 'Réunion'),
    ('Romania', 'Romania'),
    ('Russian Federation', 'Russian Federation'),
    ('Rwanda', 'Rwanda'),
    ('Saint Barthélemy', 'Saint Barthélemy'),
    ('Saint Helena, Ascension and Tristan da Cunha',
     'Saint Helena, Ascension and Tristan da Cunha'),
    ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'),
    ('Saint Lucia', 'Saint Lucia'),
    ('Saint Martin (French part)', 'Saint Martin (French part)'),
    ('Saint Pierre and Miquelon', 'Saint Pierre and Miquelon'),
    ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'),
    ('Samoa', 'Samoa'),
    ('San Marino', 'San Marino'),
    ('Sao Tome and Principe', 'Sao Tome and Principe'),
    ('Saudi Arabia', 'Saudi Arabia'),
    ('Senegal', 'Senegal'),
    ('Serbia', 'Serbia'),
    ('Seychelles', 'Seychelles'),
    ('Sierra Leone', 'Sierra Leone'),
    ('Singapore', 'Singapore'),
    ('Sint Maarten (Dutch part)', 'Sint Maarten (Dutch part)'),
    ('Slovakia', 'Slovakia'),
    ('Slovenia', 'Slovenia'),
    ('Solomon Islands', 'Solomon Islands'),
    ('Somalia', 'Somalia'),
    ('South Africa', 'South Africa'),
    ('South Georgia and the South Sandwich Islands',
     'South Georgia and the South Sandwich Islands'),
    ('Spain', 'Spain'),
    ('Sri Lanka', 'Sri Lanka'),
    ('Sudan', 'Sudan'),
    ('Suriname', 'Suriname'),
    ('South Sudan', 'South Sudan'),
    ('Svalbard and Jan Mayen', 'Svalbard and Jan Mayen'),
    ('Swaziland', 'Swaziland'),
    ('Sweden', 'Sweden'),
    ('Switzerland', 'Switzerland'),
    ('Syrian Arab Republic', 'Syrian Arab Republic'),
    ('Taiwan, Province of China', 'Taiwan, Province of China'),
    ('Tajikistan', 'Tajikistan'),
    ('Tanzania, United Republic of', 'Tanzania, United Republic of'),
    ('Thailand', 'Thailand'),
    ('Timor-Leste', 'Timor-Leste'),
    ('Togo', 'Togo'),
    ('Tokelau', 'Tokelau'),
    ('Tonga', 'Tonga'),
    ('Trinidad and Tobago', 'Trinidad and Tobago'),
    ('Tunisia', 'Tunisia'),
    ('Turkey', 'Turkey'),
    ('Turkmenistan', 'Turkmenistan'),
    ('Turks and Caicos Islands', 'Turks and Caicos Islands'),
    ('Tuvalu', 'Tuvalu'),
    ('Uganda', 'Uganda'),
    ('Ukraine', 'Ukraine'),
    ('United Arab Emirates', 'United Arab Emirates'),
    ('United Kingdom', 'United Kingdom'),
    ('United States', 'United States'),
    ('United States Minor Outlying Islands',
     'United States Minor Outlying Islands'),
    ('Uruguay', 'Uruguay'),
    ('Uzbekistan', 'Uzbekistan'),
    ('Vanuatu', 'Vanuatu'),
    ('Venezuela, Bolivarian Republic of', 'Venezuela, Bolivarian Republic of'),
    ('Viet Nam', 'Viet Nam'),
    ('Virgin Islands, British', 'Virgin Islands, British'),
    ('Virgin Islands, U.S.', 'Virgin Islands, U.S.'),
    ('Wallis and Futuna', 'Wallis and Futuna'),
    ('Yemen', 'Yemen'),
    ('Zambia', 'Zambia'),
    ('Zimbabwe', 'Zimbabwe'),
]

MY_CONSTANTS = {
    'MONTH_CHOICES': MONTH_CHOICES,
    'WRK_STATUS_CHOICES': WRK_STATUS_CHOICES,
    'CMP_STATUS_CHOICES': CMP_STATUS_CHOICES,
    'STYLE_CHOICES': STYLE_CHOICES,
    'RELATIONSHIP_CHOICES': RELATIONSHIP_CHOICES,
    'NATIONALITY_CHOICES': NATIONALITY_CHOICES
}

WRESTLING_MOVES_CHOICES = [
    ("450 Splash","450 Splash"),
    ("630 Splash","630 Splash"),
    ("Anaconda Squeeze","Anaconda Squeeze"),
    ("Anaconda Vice","Anaconda Vice"),
    ("Apron DDT","Apron DDT"),
    ("Arm Trap Neckbreaker","Arm Trap Neckbreaker"),
    ("Armbar","Armbar"),
    ("Atomic Drop","Atomic Drop"),
    ("Atomic Leg Drop","Atomic Leg Drop"),
    ("Backbreaker","Backbreaker"),
    ("Backstabber","Backstabber"),
    ("Belly-to-Belly Suplex","Belly-to-Belly Suplex"),
    ("Bicycle Kick","Bicycle Kick"),
    ("Blue Thunder Bomb","Blue Thunder Bomb"),
    ("Boma Ye","Boma Ye"),
    ("Bulldog","Bulldog"),
    ("Canadian Destroyer","Canadian Destroyer"),
    ("Chokeslam","Chokeslam"),
    ("Clothesline","Clothesline"),
    ("Codebreaker","Codebreaker"),
    ("Coquina Clutch","Coquina Clutch"),
    ("Corkscrew Elbow Drop","Corkscrew Elbow Drop"),
    ("Corner-to-Corner Missile Dropkick","Corner-to-Corner Missile Dropkick"),
    ("Crossbody Block","Crossbody Block"),
    ("Crossface","Crossface"),
    ("Crucifix Armbar","Crucifix Armbar"),
    ("Curb Stomp","Curb Stomp"),
    ("DDT","DDT"),
    ("Discus Clothesline","Discus Clothesline"),
    ("Discus Elbow Smash","Discus Elbow Smash"),
    ("Diving Cross Chop","Diving Cross Chop"),
    ("Diving Crossbody","Diving Crossbody"),
    ("Diving Headbutt","Diving Headbutt"),
    ("Diving Shoulder Block","Diving Shoulder Block"),
    ("Double Chickenwing Facebuster","Double Chickenwing Facebuster"),
    ("Double Knee Facebreaker","Double Knee Facebreaker"),
    ("Double Leg Drop","Double Leg Drop"),
    ("Double Underhook Facebuster","Double Underhook Facebuster"),
    ("Dragon Screw","Dragon Screw"),
    ("Dragon Sleeper","Dragon Sleeper"),
    ("Dropkick","Dropkick"),
    ("Elbow Drop","Elbow Drop"),
    ("Electric Chair Drop","Electric Chair Drop"),
    ("Electric Chair Facebuster","Electric Chair Facebuster"),
    ("Enzuigiri","Enzuigiri"),
    ("Exploder Suplex","Exploder Suplex"),
    ("F5","F5"),
    ("FU","FU"),
    ("Figure Four Leglock","Figure Four Leglock"),
    ("Fireman's Carry Neckbreaker","Fireman's Carry Neckbreaker"),
    ("Fireman's Carry Slam","Fireman's Carry Slam"),
    ("Fisherman Suplex","Fisherman Suplex"),
    ("Five Knuckle Shuffle","Five Knuckle Shuffle"),
    ("Flying Clothesline","Flying Clothesline"),
    ("Flying Elbow Drop","Flying Elbow Drop"),
    ("Frog Splash","Frog Splash"),
    ("German Suplex","German Suplex"),
    ("Hurracanrana","Hurracanrana"),
    ("Hurricane DDT","Hurricane DDT"),
    ("Hurricanrana","Hurricanrana"),
    ("Hurricanrana DDT","Hurricanrana DDT"),
    ("Inverted Atomic Drop","Inverted Atomic Drop"),
    ("Inverted Facelock Backbreaker","Inverted Facelock Backbreaker"),
    ("Inverted Frankensteiner","Inverted Frankensteiner"),
    ("Lariat","Lariat"),
    ("Lariat Takedown","Lariat Takedown"),
    ("Leg Sweep","Leg Sweep"),
    ("Lion's Roar (Running Double Knee Strike)","Lion's Roar (Running Double Knee Strike)"),
    ("Lionault","Lionault"),
    ("Moonsault","Moonsault"),
    ("Moonsault Double Foot Stomp","Moonsault Double Foot Stomp"),
    ("Moonsault Slam","Moonsault Slam"),
    ("Neckbreaker","Neckbreaker"),
    ("Northern Lights Suplex","Northern Lights Suplex"),
    ("Pedigree","Pedigree"),
    ("Pele Kick","Pele Kick"),
    ("Phoenix Splash","Phoenix Splash"),
    ("Piledriver","Piledriver"),
    ("Pop-up Hurricanrana","Pop-up Hurricanrana"),
    ("Pop-up Powerbomb","Pop-up Powerbomb"),
    ("Powerbomb","Powerbomb"),
    ("RKO","RKO"),
    ("Reverse STO","Reverse STO"),
    ("Rolling Cutter","Rolling Cutter"),
    ("Rolling Double Foot Stomp","Rolling Double Foot Stomp"),
    ("Rolling Elbow","Rolling Elbow"),
    ("Rolling Fireman's Carry Neckbreaker","Rolling Fireman's Carry Neckbreaker"),
    ("Rolling Fireman's Carry Slam","Rolling Fireman's Carry Slam"),
    ("Rolling Kneebar","Rolling Kneebar"),
    ("Rolling Koppu Kick","Rolling Koppu Kick"),
    ("Rolling Neck Snap","Rolling Neck Snap"),
    ("Rolling Samoan Drop","Rolling Samoan Drop"),
    ("Rolling Senton","Rolling Senton"),
    ("Rolling Thunder","Rolling Thunder"),
    ("Rolling Thunder","Rolling Thunder"),
    ("Rolling Thunder Bomb","Rolling Thunder Bomb"),
    ("Rolling Yoshi Tonic","Rolling Yoshi Tonic"),
    ("Running Apron Senton","Running Apron Senton"),
    ("Running Avalanche Bulldog","Running Avalanche Bulldog"),
    ("Running Back Elbow","Running Back Elbow"),
    ("Running Belly-to-Back Suplex","Running Belly-to-Back Suplex"),
    ("Running Belly-to-Belly Suplex","Running Belly-to-Belly Suplex"),
    ("Running Big Boot","Running Big Boot"),
    ("Running Bulldog","Running Bulldog"),
    ("Running Bulldog","Running Bulldog"),
    ("Running Calf Kick","Running Calf Kick"),
    ("Running Corner Dropkick","Running Corner Dropkick"),
    ("Running Cross Chop","Running Cross Chop"),
    ("Running Crossbody","Running Crossbody"),
    ("Running Crucifix Headscissors","Running Crucifix Headscissors"),
    ("Running DDT","Running DDT"),
    ("Running Double Chickenwing Facebuster","Running Double Chickenwing Facebuster"),
    ("Running Double Foot Stomp","Running Double Foot Stomp"),
    ("Running Double Knee Strike","Running Double Knee Strike"),
    ("Running Double Knee Strike","Running Double Knee Strike"),
    ("Running Double Leg Drop","Running Double Leg Drop"),
    ("Running Dragon Screw","Running Dragon Screw"),
    ("Running Dragon Sleeper","Running Dragon Sleeper"),
    ("Running Dropkick to Seated Opponent","Running Dropkick to Seated Opponent"),
    ("Running Dropkick to Seated Opponent","Running Dropkick to Seated Opponent"),
    ("Running Enzuigiri","Running Enzuigiri"),
    ("Running Fisherman Suplex","Running Fisherman Suplex"),
    ("Running Flying Forearm","Running Flying Forearm"),
    ("Running Forearm Smash","Running Forearm Smash"),
    ("Running Forearm Smash","Running Forearm Smash"),
    ("Running Forearm Smash","Running Forearm Smash"),
    ("Running Knee Lift","Running Knee Lift"),
    ("Running Knee Strike","Running Knee Strike"),
    ("Running Knee Trembler","Running Knee Trembler"),
    ("Running Knee Trembler","Running Knee Trembler"),
    ("Running Lariat Takedown","Running Lariat Takedown"),
    ("Running Leaping Neckbreaker","Running Leaping Neckbreaker"),
    ("Running Leg Drop Bulldog","Running Leg Drop Bulldog"),
    ("Running Leg Lariat","Running Leg Lariat"),
    ("Running Leg Lariat","Running Leg Lariat"),
    ("Running Leg Sweep","Running Leg Sweep"),
    ("Running Neckbreaker","Running Neckbreaker"),
    ("Running Overhead Kick","Running Overhead Kick"),
    ("Running Phoenix Splash","Running Phoenix Splash"),
    ("Running Pop-up Powerbomb","Running Pop-up Powerbomb"),
    ("Running Power Slam","Running Power Slam"),
    ("Running Reverse Bulldog","Running Reverse Bulldog"),
    ("Running Reverse Neckbreaker","Running Reverse Neckbreaker"),
    ("Running Reverse STO","Running Reverse STO"),
    ("Running Rolling Cutter","Running Rolling Cutter"),
    ("Running Rolling Elbow","Running Rolling Elbow"),
    ("Running Rolling Elbow Smash","Running Rolling Elbow Smash"),
    ("Running Rolling Kneebar","Running Rolling Kneebar"),
    ("Running Rolling Senton","Running Rolling Senton"),
    ("Running Rolling Thunder","Running Rolling Thunder"),
    ("Running Rolling Yoshi Tonic","Running Rolling Yoshi Tonic"),
    ("Running Samoan Drop","Running Samoan Drop"),
    ("Running Shooting Star Press","Running Shooting Star Press"),
    ("Running Side Slam","Running Side Slam"),
    ("Running Sitout Powerbomb","Running Sitout Powerbomb"),
    ("Running Sling Blade","Running Sling Blade"),
    ("Running Snapmare Driver","Running Snapmare Driver"),
    ("Running Somersault Senton","Running Somersault Senton"),
    ("Running Somersault Senton","Running Somersault Senton"),
    ("Running Spinebuster","Running Spinebuster"),
    ("Running Spinning Heel Kick","Running Spinning Heel Kick"),
    ("Running Suicide Senton","Running Suicide Senton"),
    ("Running Superplex","Running Superplex"),
    ("Running Swanton Bomb","Running Swanton Bomb"),
    ("Running Swinging DDT","Running Swinging DDT"),
    ("Running Swinging Leg Sweep","Running Swinging Leg Sweep"),
    ("Running Swinging Neckbreaker","Running Swinging Neckbreaker"),
    ("Running Tiger Feint Kick","Running Tiger Feint Kick"),
    ("Running Tilt-a-Whirl Backbreaker","Running Tilt-a-Whirl Backbreaker"),
    ("Running Tilt-a-Whirl DDT","Running Tilt-a-Whirl DDT"),
    ("Running Tilt-a-Whirl Facebuster","Running Tilt-a-Whirl Facebuster"),
    ("Running Top Rope Corkscrew 450 Splash","Running Top Rope Corkscrew 450 Splash"),
    ("Running Top Rope Cross Chop","Running Top Rope Cross Chop"),
    ("Running Top Rope DDT","Running Top Rope DDT"),
    ("Running Top Rope Double Chickenwing Facebuster","Running Top Rope Double Chickenwing Facebuster"),
    ("Running Top Rope Double Foot Stomp","Running Top Rope Double Foot Stomp"),
    ("Running Top Rope Double Leg Drop","Running Top Rope Double Leg Drop"),
    ("Running Top Rope Dragon Sleeper","Running Top Rope Dragon Sleeper"),
    ("Running Top Rope Hurricanrana","Running Top Rope Hurricanrana"),
    ("Running Top Rope Hurricanrana DDT","Running Top Rope Hurricanrana DDT"),
    ("Running Top Rope Leaping Clothesline","Running Top Rope Leaping Clothesline"),
    ("Running Top Rope Leaping Neckbreaker","Running Top Rope Leaping Neckbreaker"),
    ("Running Top Rope Pop-up Powerbomb","Running Top Rope Pop-up Powerbomb"),
    ("Running Top Rope Rolling Thunder","Running Top Rope Rolling Thunder"),
    ("Running Top Rope Running Leaping Clothesline","Running Top Rope Running Leaping Clothesline"),
    ("Running Top Rope Running Leaping Neckbreaker","Running Top Rope Running Leaping Neckbreaker"),
    ("Running Top Rope Running Rolling Thunder","Running Top Rope Running Rolling Thunder"),
    ("Running Top Rope Running Top Rope Corkscrew 450 Splash","Running Top Rope Running Top Rope Corkscrew 450 Splash"),
    ("Running Top Rope Running Top Rope Dragon Sleeper","Running Top Rope Running Top Rope Dragon Sleeper"),
    ("Running Top Rope Running Top Rope Hurricanrana DDT","Running Top Rope Running Top Rope Hurricanrana DDT"),
    ("Running Top Rope Running Top Rope Saito Suplex","Running Top Rope Running Top Rope Saito Suplex"),
    ("Running Top Rope Saito Suplex","Running Top Rope Saito Suplex"),
    ("Running Top Rope Samoan Drop","Running Top Rope Samoan Drop"),
    ("Running Top Rope Swinging Leg Sweep","Running Top Rope Swinging Leg Sweep"),
    ("Running Top Rope Swinging Neckbreaker","Running Top Rope Swinging Neckbreaker"),
    ("Running Top Rope Tornado Punch","Running Top Rope Tornado Punch"),
    ("Running Tornado DDT","Running Tornado DDT"),
    ("Running Tornado Kick","Running Tornado Kick"),
    ("Running Tornado Punch","Running Tornado Punch"),
    ("Running Uppercut","Running Uppercut"),
    ("Running Wheel Kick","Running Wheel Kick"),
    ("Running Wheelbarrow Facebuster","Running Wheelbarrow Facebuster"),
    ("Russian Leg Sweep","Russian Leg Sweep"),
    ("Saito Suplex","Saito Suplex"),
    ("Samoan Drop","Samoan Drop"),
    ("Sharpshooter","Sharpshooter"),
    ("Sharpshooter","Sharpshooter"),
    ("Shiranui","Shiranui"),
    ("Shooting Star Press","Shooting Star Press"),
    ("Sitout Powerbomb","Sitout Powerbomb"),
    ("Sleeper Hold","Sleeper Hold"),
    ("Sling Blade","Sling Blade"),
    ("Slingshot Crossbody","Slingshot Crossbody"),
    ("Slingshot Somersault Plancha","Slingshot Somersault Plancha"),
    ("Snapmare Driver","Snapmare Driver"),
    ("Snapmare Driver","Snapmare Driver"),
    ("Spear","Spear"),
    ("Spinebuster","Spinebuster"),
    ("Spiral Tap","Spiral Tap"),
    ("Springboard 450 Splash","Springboard 450 Splash"),
    ("Springboard Arm Drag","Springboard Arm Drag"),
    ("Springboard Backstabber","Springboard Backstabber"),
    ("Springboard Bulldog","Springboard Bulldog"),
    ("Springboard Corkscrew Crossbody","Springboard Corkscrew Crossbody"),
    ("Springboard Crossbody Block","Springboard Crossbody Block"),
    ("Springboard DDT","Springboard DDT"),
    ("Springboard Diving Headbutt","Springboard Diving Headbutt"),
    ("Springboard Double Foot Stomp","Springboard Double Foot Stomp"),
    ("Springboard Dropkick","Springboard Dropkick"),
    ("Springboard Guillotine Leg Drop","Springboard Guillotine Leg Drop"),
    ("Springboard Hurricanrana","Springboard Hurricanrana"),
    ("Springboard Leg Drop","Springboard Leg Drop"),
    ("Springboard Moonsault","Springboard Moonsault"),
    ("Springboard Moonsault Slam","Springboard Moonsault Slam"),
    ("Springboard Neckbreaker","Springboard Neckbreaker"),
    ("Springboard Rolling Fireman's Carry Neckbreaker","Springboard Rolling Fireman's Carry Neckbreaker"),
    ("Springboard Rolling Thunder","Springboard Rolling Thunder"),
    ("Springboard Running Top Rope DDT","Springboard Running Top Rope DDT"),
    ("Springboard Saito Suplex","Springboard Saito Suplex"),
    ("Springboard Samoan Drop","Springboard Samoan Drop"),
    ("Springboard Superkick","Springboard Superkick"),
    ("Springboard Tornado DDT","Springboard Tornado DDT"),
    ("Standing Corkscrew Moonsault","Standing Corkscrew Moonsault"),
    ("Standing Moonsault","Standing Moonsault"),
    ("Standing Shooting Star Press","Standing Shooting Star Press"),
    ("Standing Shooting Star Press","Standing Shooting Star Press"),
    ("Standing Spanish Fly","Standing Spanish Fly"),
    ("Stepover Toehold Facelock","Stepover Toehold Facelock"),
    ("Stone Cold Stunner","Stone Cold Stunner"),
    ("Suicide Dive","Suicide Dive"),
    ("Sunset Flip Powerbomb","Sunset Flip Powerbomb"),
    ("Superkick","Superkick"),
    ("Superplex","Superplex"),
    ("Suplex","Suplex"),
    ("Swanton Bomb","Swanton Bomb"),
    ("Swinging DDT","Swinging DDT"),
    ("Swinging DDT","Swinging DDT"),
    ("Swinging Fisherman Suplex","Swinging Fisherman Suplex"),
    ("Swinging Neckbreaker","Swinging Neckbreaker"),
    ("Swinging Side Slam","Swinging Side Slam"),
    ("Swinging Side Slam","Swinging Side Slam"),
    ("Swinging Sleeper Slam","Swinging Sleeper Slam"),
    ("Tiger Feint Kick","Tiger Feint Kick"),
    ("Tilt-a-Whirl Backbreaker","Tilt-a-Whirl Backbreaker"),
    ("Tilt-a-Whirl Headscissors Takedown","Tilt-a-Whirl Headscissors Takedown"),
    ("Tombstone Piledriver","Tombstone Piledriver"),
    ("Top Rope Belly-to-Belly Suplex","Top Rope Belly-to-Belly Suplex"),
    ("Top Rope Corkscrew 450 Splash","Top Rope Corkscrew 450 Splash"),
    ("Top Rope Crossbody Block","Top Rope Crossbody Block"),
    ("Top Rope DDT","Top Rope DDT"),
    ("Top Rope Double Foot Stomp","Top Rope Double Foot Stomp"),
    ("Top Rope Double Knee Drop","Top Rope Double Knee Drop"),
    ("Top Rope Double Knee Facebreaker","Top Rope Double Knee Facebreaker"),
    ("Top Rope Double Knee Facebreaker","Top Rope Double Knee Facebreaker"),
    ("Top Rope Double Leg Drop","Top Rope Double Leg Drop"),
    ("Top Rope Double Underhook Suplex","Top Rope Double Underhook Suplex"),
    ("Top Rope Dragon Screw","Top Rope Dragon Screw"),
    ("Top Rope Dragonrana","Top Rope Dragonrana"),
    ("Top Rope Fireman's Carry Neckbreaker","Top Rope Fireman's Carry Neckbreaker"),
    ("Top Rope Fireman's Carry Neckbreaker","Top Rope Fireman's Carry Neckbreaker"),
    ("Top Rope Frankensteiner","Top Rope Frankensteiner"),
    ("Top Rope Hurricanrana","Top Rope Hurricanrana"),
    ("Top Rope Hurricanrana DDT","Top Rope Hurricanrana DDT"),
    ("Top Rope Leaping Clothesline","Top Rope Leaping Clothesline"),
    ("Top Rope Leaping Neckbreaker","Top Rope Leaping Neckbreaker"),
    ("Top Rope Leg Drop","Top Rope Leg Drop"),
    ("Top Rope Moonsault Double Knee Drop","Top Rope Moonsault Double Knee Drop"),
    ("Top Rope Phoenix Splash","Top Rope Phoenix Splash"),
    ("Top Rope Powerbomb","Top Rope Powerbomb"),
    ("Top Rope Reverse DDT","Top Rope Reverse DDT"),
    ("Top Rope Rolling Cutter","Top Rope Rolling Cutter"),
    ("Top Rope Rolling Double Foot Stomp","Top Rope Rolling Double Foot Stomp"),
    ("Top Rope Rolling Double Foot Stomp","Top Rope Rolling Double Foot Stomp"),
    ("Top Rope Rolling Elbow","Top Rope Rolling Elbow"),
    ("Top Rope Rolling Senton","Top Rope Rolling Senton"),
    ("Top Rope Rolling Senton","Top Rope Rolling Senton"),
    ("Top Rope Rolling Thunder Bomb","Top Rope Rolling Thunder Bomb"),
    ("Top Rope Rolling Yoshi Tonic","Top Rope Rolling Yoshi Tonic"),
    ("Top Rope Rolling Yoshi Tonic","Top Rope Rolling Yoshi Tonic"),
    ("Top Rope Running Avalanche Bulldog","Top Rope Running Avalanche Bulldog"),
    ("Top Rope Running Bulldog","Top Rope Running Bulldog"),
    ("Top Rope Running Bulldog","Top Rope Running Bulldog"),
    ("Top Rope Running Clothesline","Top Rope Running Clothesline"),
    ("Top Rope Running Crossbody Block","Top Rope Running Crossbody Block"),
    ("Top Rope Running Dragon Screw","Top Rope Running Dragon Screw"),
    ("Top Rope Running Flying Forearm","Top Rope Running Flying Forearm"),
    ("Top Rope Running Knee Lift","Top Rope Running Knee Lift"),
    ("Top Rope Running Leaping Neckbreaker","Top Rope Running Leaping Neckbreaker"),
    ("Top Rope Running Leg Lariat","Top Rope Running Leg Lariat"),
    ("Top Rope Running Phoenix Splash","Top Rope Running Phoenix Splash"),
    ("Top Rope Running Reverse Bulldog","Top Rope Running Reverse Bulldog"),
    ("Top Rope Running Rolling Cutter","Top Rope Running Rolling Cutter"),
    ("Top Rope Running Rolling Elbow","Top Rope Running Rolling Elbow"),
    ("Top Rope Running Rolling Elbow Smash","Top Rope Running Rolling Elbow Smash"),
    ("Top Rope Running Rolling Kneebar","Top Rope Running Rolling Kneebar"),
    ("Top Rope Running Sling Blade","Top Rope Running Sling Blade"),
    ("Top Rope Running Swanton Bomb","Top Rope Running Swanton Bomb"),
    ("Top Rope Running Swanton Bomb","Top Rope Running Swanton Bomb"),
    ("Top Rope Running Swinging DDT","Top Rope Running Swinging DDT"),
    ("Top Rope Running Swinging Fisherman Suplex","Top Rope Running Swinging Fisherman Suplex"),
    ("Top Rope Running Swinging Neckbreaker","Top Rope Running Swinging Neckbreaker"),
    ("Top Rope Running Tilt-a-Whirl Facebuster","Top Rope Running Tilt-a-Whirl Facebuster"),
    ("Top Rope Running Top Rope Double Foot Stomp","Top Rope Running Top Rope Double Foot Stomp"),
    ("Top Rope Running Top Rope Dragon Screw","Top Rope Running Top Rope Dragon Screw"),
    ("Top Rope Running Top Rope Flying Forearm","Top Rope Running Top Rope Flying Forearm"),
    ("Top Rope Running Top Rope Hurricanrana","Top Rope Running Top Rope Hurricanrana"),
    ("Top Rope Running Top Rope Leg Lariat","Top Rope Running Top Rope Leg Lariat"),
    ("Top Rope Running Top Rope Reverse Bulldog","Top Rope Running Top Rope Reverse Bulldog"),
    ("Top Rope Running Top Rope Rolling Elbow Smash","Top Rope Running Top Rope Rolling Elbow Smash"),
    ("Top Rope Running Top Rope Samoan Drop","Top Rope Running Top Rope Samoan Drop"),
    ("Top Rope Running Top Rope Sling Blade","Top Rope Running Top Rope Sling Blade"),
    ("Top Rope Running Top Rope Swinging DDT","Top Rope Running Top Rope Swinging DDT"),
    ("Top Rope Running Top Rope Tilt-a-Whirl Facebuster","Top Rope Running Top Rope Tilt-a-Whirl Facebuster"),
    ("Top Rope Running Top Rope Tornado Punch","Top Rope Running Top Rope Tornado Punch"),
    ("Top Rope Running Top Rope Wheel Kick","Top Rope Running Top Rope Wheel Kick"),
    ("Top Rope Running Tornado Kick","Top Rope Running Tornado Kick"),
    ("Top Rope Running Wheel Kick","Top Rope Running Wheel Kick"),
    ("Top Rope Shooting Star Press","Top Rope Shooting Star Press"),
    ("Top Rope Somersault Senton","Top Rope Somersault Senton"),
    ("Top Rope Spinning Heel Kick","Top Rope Spinning Heel Kick"),
    ("Top Rope Springboard Guillotine Leg Drop","Top Rope Springboard Guillotine Leg Drop"),
    ("Top Rope Springboard Guillotine Leg Drop","Top Rope Springboard Guillotine Leg Drop"),
    ("Top Rope Springboard Moonsault","Top Rope Springboard Moonsault"),
    ("Top Rope Springboard Moonsault","Top Rope Springboard Moonsault"),
    ("Top Rope Springboard Moonsault Slam","Top Rope Springboard Moonsault Slam"),
    ("Top Rope Springboard Rolling Thunder","Top Rope Springboard Rolling Thunder"),
    ("Top Rope Springboard Samoan Drop","Top Rope Springboard Samoan Drop"),
    ("Top Rope Swanton Bomb","Top Rope Swanton Bomb"),
    ("Top Rope Swinging Fisherman Suplex","Top Rope Swinging Fisherman Suplex"),
    ("Top Rope Tornado DDT","Top Rope Tornado DDT"),
    ("Top Rope Tornado Punch","Top Rope Tornado Punch"),
    ("Tornado DDT","Tornado DDT"),
    ("Tornado Kick","Tornado Kick"),
    ("Tornado Punch","Tornado Punch"),
    ("Triangle Choke","Triangle Choke"),
    ("Wheelbarrow Facebuster","Wheelbarrow Facebuster"),
    ("Wristlock","Wristlock"),
]
# remove duplicates pairs from WRESTLING_MOVES_CHOICES
WRESTLING_MOVES_CHOICES = list(dict.fromkeys(WRESTLING_MOVES_CHOICES))