# Generated by Django 5.0.1 on 2024-01-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supersim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Femake'), ('other', 'Other')], default='male', max_length=20),
        ),
    ]
