# Generated by Django 5.0.1 on 2024-01-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supersim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrestler',
            name='style',
            field=models.CharField(choices=[('Brawler', 'Brawler'), ('High Flyer', 'High Flyer'), ('Powerhouse', 'Powerhouse'), ('Technician', 'Technician'), ('All-Rounder', 'All-Rounder'), ('Gimmick', 'Gimmick'), ('Other', 'Other')], default='Brawler', max_length=50),
        ),
    ]
