# Generated by Django 5.0.1 on 2024-01-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supersim', '0002_alter_wrestler_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrestler',
            name='image',
            field=models.CharField(default='./pictures/people/++MALE 0001.jpg.png', max_length=200),
        ),
    ]
