# Generated by Django 5.0.1 on 2024-01-16 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supersim', '0003_company_image_alter_wrestler_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wrestler',
            old_name='physique',
            new_name='intimidating',
        ),
        migrations.AddField(
            model_name='wrestler',
            name='sex_appeal',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='wrestler',
            name='star_quality',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20),
        ),
    ]
