# Generated by Django 5.0.1 on 2024-01-15 03:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supersim', '0004_wrestler_acting_wrestler_aerial_wrestler_ambitious_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('year_of_founding', models.PositiveIntegerField()),
                ('month_of_founding', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Opened'), (1, 'Closed')], default=0)),
                ('money', models.IntegerField()),
                ('overness', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('momentum', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='wrestler',
            name='momentum',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='wrestler',
            name='month_of_birth',
            field=models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrestler',
            name='year_of_birth',
            field=models.PositiveIntegerField(default=1990),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='acting',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='aerial',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='ambitious',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='brawl',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='charisma',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='commentary',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='condition',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='overness',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='physique',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='power',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='psychology',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='referee',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='road_agent',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='sociable',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='stamina',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='style',
            field=models.CharField(choices=[('Brawler', 'Brawler'), ('High Flyer', 'High Flyer'), ('Powerhouse', 'Powerhouse'), ('Technician', 'Technician'), ('All-Rounder', 'All-Rounder'), ('Gimmick', 'Gimmick'), ('Comedy', 'Comedy'), ('Hardcore', 'Hardcore'), ('Luchador', 'Luchador'), ('Other', 'Other')], default='Brawler', max_length=50),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='technical',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('starting_year', models.PositiveIntegerField()),
                ('ending_month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('ending_year', models.PositiveIntegerField()),
                ('salary', models.IntegerField()),
                ('exclusivity_type', models.CharField(choices=[('exclusive', 'Exclusive'), ('non-exclusive', 'Non-Exclusive')], max_length=20)),
                ('written_contract', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supersim.company')),
                ('wrestler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supersim.wrestler')),
            ],
        ),
        migrations.CreateModel(
            name='WrestlerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('friends', 'Friends'), ('rivals', 'Rivals'), ('lovers', 'Lovers'), ('pupil', 'Pupil')], max_length=20)),
                ('starting_month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('starting_year', models.PositiveIntegerField()),
                ('from_Wrestler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_Wrestler', to='supersim.wrestler')),
                ('to_Wrestler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_Wrestler', to='supersim.wrestler')),
            ],
            options={
                'unique_together': {('from_Wrestler', 'to_Wrestler', 'relationship_type')},
            },
        ),
    ]
