# Generated by Django 5.0.1 on 2024-01-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supersim', '0004_rename_physique_wrestler_intimidating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrestler',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='style',
            field=models.CharField(choices=[('brawler', 'Brawler'), ('high Flyer', 'High Flyer'), ('powerhouse', 'Powerhouse'), ('technician', 'Technician'), ('all-rounder', 'All-Rounder'), ('gimmick', 'Gimmick'), ('comedy', 'Comedy'), ('showman', 'Showman'), ('hardcore', 'Hardcore'), ('luchador', 'Luchador'), ('strong style', 'Strong Style'), ('other', 'Other')], default='all-rounder', max_length=50),
        ),
    ]
