# Generated by Django 5.0.1 on 2024-01-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supersim', '0005_company_wrestler_momentum_wrestler_month_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrestler',
            name='age',
        ),
    ]
