# Generated by Django 5.0.1 on 2024-01-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supersim', '0006_remove_wrestler_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrestler',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='style',
            field=models.CharField(choices=[('Brawler', 'Brawler'), ('High Flyer', 'High Flyer'), ('Powerhouse', 'Powerhouse'), ('Technician', 'Technician'), ('All-Rounder', 'All-Rounder'), ('Gimmick', 'Gimmick'), ('Comedy', 'Comedy'), ('Hardcore', 'Hardcore'), ('Luchador', 'Luchador'), ('Strong Style', 'Strong Style'), ('Other', 'Other')], default='Brawler', max_length=50),
        ),
    ]
